FROM airflow-local

RUN mkdir -p /home/root/airflow/dags
COPY dags/* /home/root/airflow/dags

# initialize the database
RUN airflow initdb

# Make port 80 available to the world outside this container
EXPOSE 80

# Run the service when the container launches
CMD ["sh", "-c", "airflow webserver -p 80 -D; airflow scheduler -D"]


