# FIRST IMAGE BUILD TAKES WHILE. COMMENT FROM AIRFLO-LOCAL and UNCOMMENT FROM ALPINE:3.6 FOR THE FIRST RUN
FROM alpine:3.6

RUN apk add --no-cache python3 python3-dev musl-dev util-linux linux-headers openssl-dev openssl git g++ libxml2-dev libxslt-dev gcc libffi libffi-dev sudo

RUN apk --update add bash

ENV SLUGIFY_USES_TEXT_UNIDECODE=yes

ENV AIRFLOW_HOME=/home/root/airflow

# install from pypi using pip
RUN pip3 install airflow