apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-local-app
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: airflow-local-app
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow-local-app
    spec:
      containers:
      - name: airflow-local-app
        image: airflow-local-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80

